[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.8"
hooks = [{ id = "actionlint" }]

[[repos]]
repo = "builtin"
hooks = [
    { id = "fix-byte-order-marker" },
    { id = "check-json" },
    { id = "check-yaml" },
    { id = "check-toml" },
    { id = "mixed-line-ending" },
    { id = "check-symlinks" },
    { id = "check-merge-conflict" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff-check"
language = "system"
entry = "uv run ruff check --fix"
files = "\\.py$"

[[repos.hooks]]
id = "ruff-format"
name = "ruff-format"
language = "system"
entry = "uv run ruff format"
files = "\\.py$"

[[repos.hooks]]
id = "editorconfig-checker"
name = "editorconfig-checker"
language = "system"
entry = "uv run ec"
files = ".*"

[[repos.hooks]]
id = "djade"
name = "djade"
language = "system"
entry = "uv run djade"
files = "\\.html$"
