[book]
authors = ["David Reed"]
language = "en"
src = "src"
title = "Stave"
description = "Documentation for Stave, managing events and volunteer staffing for roller derby."

[output.html]
git-repository-url = "https://github.com/davidmreed/stave"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
